server:
  port: 80

spring:
  application:
    name: cloud-order-service
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群
#      defaultZone: http://localhost:7001/eureka #单机版本



