server:
  port: 7001

eureka:
  instance:
    hostname: eureke7001.com #eureka服务端的实例名字
  client:
    register-with-eureka: false #表示不向注册中心注册自己
    fetch-registry: false  #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://eureka7002.com:7002/eureka/ 集群版，以下是单机版
      defaultZone: http://eureka7002.com:7002/eureka/
  server:
    #关闭Eureka的自我保护机制，保证不可用服务马上被剔除
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000

